
const express = require('express')
const bodyParser = require('body-parser')
const app = express();
app.use(bodyParser.json());
const counselingRoutes = require('./routes/counselingRoutes.js');
const cancelSessionRoutes = require('./routes/cancelSessionRoutes.js');
const patientSessionsRoutes = require('./routes/getPatientSessionsRoutes.js');
const doctorSessionsRoutes = require('./routes/getDoctorSessionsRoutes.js');
const supportGroupsRoutes = require('./routes/supportGroupsRoutes.js');
const updateSupportGroupRoutes = require('./routes/updateSupportGroupRoutes.js');
const deleteSupportGroupRoutes = require('./routes/deleteSupportGroupRoutes.js');
const supportGroupMembersRoutes = require('./routes/supportGroupMembersRoutes.js');
const joinRequestRoutes = require('./routes/joinRequestRoutes.js');
const messagesRoutes = require('./routes/supportGroupMessagesRoutes.js');
const anonChatRoutes = require('./routes/anonChatRoutes.js');
const anonChatMessagesRoutes = require('./routes/anonChatMessagesRoutes.js');
const getAnonChatMessagesRoutes = require('./routes/getAnonChatMessagesRoutes.js');
const ngosRoutes = require('./routes/ngosRoutes.js');
const getNgosRoutes = require('./routes/getNgosRoutes.js');
const updateNgoRoutes = require('./routes/updateNgoRoutes.js');
const availabilityRoutes = require('./routes/doctorAvailabilityRoutes.js');
const getAvailabilityRoutes = require('./routes/getDoctorAvailabilityRoutes.js');
const appointmentRequestRoutes = require('./routes/appointmentRequestRoutes.js');
const appointmentApproveRoutes = require('./routes/appointmentApproveRoutes.js');
const appointmentRejectRoutes = require('./routes/appointmentRejectRoutes.js');
const getDoctorAppointmentsRoutes = require('./routes/getDoctorAppointmentsRoutes.js');
const getPatientAppointmentsRoutes = require('./routes/getPatientAppointmentsRoutes.js');
const appointmentCancelRoutes = require('./routes/appointmentCancelRoutes.js');
const surgicalMissionRoutes = require('./routes/surgicalMissionRoutes.js');
const upcomingMissionsRoutes = require('./routes/getUpcomingMissionsRoutes.js');
const missionDetailsRoutes = require('./routes/getMissionDetailsRoutes.js');
const missionRegistrationRoutes = require('./routes/missionRegistrationRoutes.js');
const missionApproveRoutes = require('./routes/missionApproveRoutes.js');
const missionRejectRoutes = require('./routes/missionRejectRoutes.js');
const missionPatientsRoutes = require('./routes/getMissionPatientsRoutes.js');
app.use('/api/ngos/update', updateNgoRoutes);
app.use('/api/ngos/all', getNgosRoutes);
//const ngosRoutes = require('./routes/ngosRoutes.js');
app.use('/api/ngos', ngosRoutes);
app.use('/api/anon-chat/messages', getAnonChatMessagesRoutes);
app.use('/api/anon-chat/messages', anonChatMessagesRoutes);
app.use('/api/anon-chat', anonChatRoutes);
app.use('/api/support-groups/messages', messagesRoutes);
app.use('/api/support-groups/members', supportGroupMembersRoutes);
app.use('/api/support-groups/delete', deleteSupportGroupRoutes);
app.use('/api/support-groups/update', updateSupportGroupRoutes);
app.use('/api/support-groups', supportGroupsRoutes);
const removeMemberRoutes = require('./routes/removeMemberRoutes.js');
app.use('/api/support-groups/members/remove', removeMemberRoutes);
app.use('/api/counseling/sessions', counselingRoutes);
app.use('/api/counseling/cancel', cancelSessionRoutes);
app.use('/api/counseling/patient', patientSessionsRoutes);
app.use('/api/counseling/doctor', doctorSessionsRoutes);
app.use('/api/support-groups/join-request', joinRequestRoutes);
app.use('/api/availability', availabilityRoutes);
app.use('/api/availability/doctor', getAvailabilityRoutes);
app.use('/api/appointments', appointmentRequestRoutes);
app.use('/api/appointments', appointmentApproveRoutes);
//console.log("appointmentRejectRoutes =", appointmentRejectRoutes);
app.use('/api/appointments', appointmentRejectRoutes);
app.use('/api/appointments/doctor', getDoctorAppointmentsRoutes);
app.use('/api/appointments/patient', getPatientAppointmentsRoutes);
app.use('/api/appointments', appointmentCancelRoutes);
app.use('/api/missions', surgicalMissionRoutes);
app.use('/api/missions', upcomingMissionsRoutes);
app.use('/api/missions/details', missionDetailsRoutes);
app.use('/api/missions', missionRegistrationRoutes);
app.use('/api/missions', missionApproveRoutes);
app.use('/api/missions', missionRejectRoutes);
app.use('/api/missions', missionPatientsRoutes);
module.exports = app;